/* The course inspector: `?debug=1`, or G at any time.

   This file exists because building a hole was the one job in this project
   with no tools. A hole is a few lines of numbers in courses.js —

       pads: [pad(0, 0, 6, 15), pad(6, 9, 5, 4, 0.8)],
       extra: [wall(2.6, 9.4, 3.6, 0.35, 0.55, { base: -0.1 })],

   — and the only way to find out what those numbers meant was to load the
   page and squint at a green field: no way to tell a pad's edge from a rail's,
   no way to see which rails `enclose()` had decided to build for you, and no
   way at all to answer the question you actually have while authoring, which
   is "what are the coordinates of *that* corner". tests.html can tell you a
   hole is broken. It cannot tell you where anything is.

   So this draws the hole the way the solver sees it, out of the same data the
   solver reads:

   - **pads** as outlines on their own surface, tilt and all, coloured by kind
     and numbered in the order courses.js lists them;
   - **walls** as their collision boxes, from `physics.wallBox()` at the
     current clock — so a gate's outline slides with the gate and a blade's
     turns with the blade, and a mesh that had drifted from its box would show
     up as two rectangles instead of one;
   - **generated rails in one colour and authored `extra` walls in another**,
     which is the quickest way to see that `enclose()` has fenced off an edge
     you meant to leave open, or left one open you meant to fence;
   - **water, gaps, the cup's rim with the clearance the tests want round it,
     and the tee**;
   - a **metre grid through the origin**, because every number in courses.js
     is a measurement from there.

   Then the part that does the real work: **the pointer reads out where it is
   on the course**, by intersecting the view ray with the pads themselves
   rather than with a flat plane, so the number is right on a ramp too. Point
   at a corner and you have the x and z to type. That is the authoring loop —
   look at the hole, point at where the thing should go, read the numbers,
   write them down — and it is the difference between building a hole and
   guessing at one.

   The panel also lints the hole against the rules a new one has to respect.
   Those rules are asserted in tests.html and **tests.html is the authority**;
   what is here is the same five checks brought forward to where you are
   editing, so a mistake answers back in the same second you make it rather
   than the next time somebody opens the suite.

   None of this costs a normal frame anything. The overlay does not exist
   until the inspector is switched on, and the panel is the only DOM this file
   ever writes. */
(function (G3) {
    'use strict';

    var C = G3.CONFIG;
    var P = G3.physics;

    /* Pads by what they do to the ball; walls by who put them there. That
       second distinction is the one worth having — a rail you did not author
       is a rail `enclose()` inferred, and inference is where holes go wrong. */
    var COLOUR = {
        green: 0x6cf07a, fairway: 0x3fd06a, wood: 0xe0a45a, sand: 0xf0e27a, rough: 0x4a9c5a,
        rail: 0x4db4ff,          // generated by enclose()
        extra: 0xff7ad9,         // authored in the hole's `extra`
        water: 0x37d5ff,
        gap: 0xff5c5c,
        cup: 0xffffff,
        tee: 0xffe066,
        grid: 0x8892a0
    };

    var D = {
        on: false,
        group: null,
        hole: null,              // what the overlay was built for
        movers: [],              // { line, wall } — replaced from wallBox each frame
        canvas: null,
        panel: null,
        point: null,             // where the pointer last landed, in world units
        pointer: null,           // …and where the pointer is, in clip space
        frames: 0, acc: 0, worst: 0, fps: 0, ms: 0,
        due: 0                   // when the panel is next allowed to be rewritten
    };

    /* ── the overlay ────────────────────────────────────────────────────── */

    function line(points, colour, close) {
        var geo = new THREE.BufferGeometry();
        var arr = new Float32Array(points.length * 3), i;
        for (i = 0; i < points.length; i++) {
            arr[i * 3] = points[i][0];
            arr[i * 3 + 1] = points[i][1];
            arr[i * 3 + 2] = points[i][2];
        }
        geo.setAttribute('position', new THREE.BufferAttribute(arr, 3));
        var mat = new THREE.LineBasicMaterial({
            // WebGL will not draw a line wider than a pixel, so the only
            // contrast available is colour and opacity. Both are spent.
            color: colour,
            // Straight through the course: an outline you can only see the
            // near half of is not an outline, it is a decoration.
            depthTest: false, fog: false
        });
        var l = new (close ? THREE.LineLoop : THREE.Line)(geo, mat);
        l.renderOrder = 900;
        return l;
    }

    /* A pad, drawn on its own surface so a ramp's outline climbs with it, and
       washed in a flat colour on top.

       The wash **alternates by index rather than by kind**, which looks like
       the wrong choice and is not. What a pad is made of is already on the
       screen — grass is green, sand is sand, a plank is a plank — and what is
       not on the screen at all is *where one pad ends and the next begins*.
       Two greens meeting are invisible until you tint them differently, and
       that seam is the thing worth looking at: it is where a hole either tiles
       cleanly or trips the ball on a step nobody meant to build. The kind is
       on the outline, and under the pointer in words. */
    var WASH = [0x00e0ff, 0xff5ad0];

    function padFill(pad, index) {
        var geo = new THREE.PlaneGeometry(pad.w, pad.d);
        geo.rotateX(-Math.PI / 2);
        // The same shear the renderer gives the pad itself, so the wash lies
        // on the ramp rather than through it.
        if (pad.sx || pad.sz) {
            var m = new THREE.Matrix4();
            m.set(1, 0, 0, 0, (pad.sx || 0), 1, (pad.sz || 0), 0, 0, 0, 1, 0, 0, 0, 0, 1);
            geo.applyMatrix4(m);
        }
        var mesh = new THREE.Mesh(geo, new THREE.MeshBasicMaterial({
            color: WASH[index % WASH.length],
            transparent: true, opacity: 0.22, depthWrite: false, fog: false,
            side: THREE.DoubleSide
        }));
        var cx = pad.x + pad.w / 2, cz = pad.z + pad.d / 2;
        // A hand's breadth above the grass: invisible from the play camera,
        // and clear of any z-fighting with the pad it is describing.
        mesh.position.set(cx, P.padHeight(pad, cx, cz) + 0.03, cz);
        mesh.renderOrder = 880;
        return mesh;
    }

    function padOutline(pad) {
        var y = function (x, z) { return P.padHeight(pad, x, z) + 0.04; };
        var x0 = pad.x, x1 = pad.x + pad.w, z0 = pad.z, z1 = pad.z + pad.d;
        return line([
            [x0, y(x0, z0), z0], [x1, y(x1, z0), z0],
            [x1, y(x1, z1), z1], [x0, y(x0, z1), z1]
        ], COLOUR[pad.kind] || COLOUR.green, true);
    }

    // A flat rectangle at a fixed height: water, and the gaps where rails were
    // deliberately not built.
    function rectOutline(r, y, colour) {
        return line([
            [r.x, y, r.z], [r.x + r.w, y, r.z],
            [r.x + r.w, y, r.z + r.d], [r.x, y, r.z + r.d]
        ], colour, true);
    }

    /* A wall, as the box the solver collides against. The geometry is a unit
       box scaled to the footprint; `syncWalls` re-places it every frame from
       wallBox(), which is what makes a gate's outline slide with the gate. */
    function wallOutline(wall, authored) {
        var box = new THREE.BoxGeometry(wall.w, wall.h, wall.d);
        var colour = authored ? COLOUR.extra : COLOUR.rail;
        var g = new THREE.Group();
        // The solid, so a rail reads as a volume at a glance; the edges, so
        // its exact footprint can still be read off against the grid.
        g.add(new THREE.Mesh(box, new THREE.MeshBasicMaterial({
            color: colour, transparent: true, opacity: 0.2,
            depthWrite: false, fog: false
        })));
        var l = new THREE.LineSegments(new THREE.EdgesGeometry(box),
            new THREE.LineBasicMaterial({ color: colour, depthTest: false, fog: false }));
        l.renderOrder = 900;
        g.add(l);
        g.renderOrder = 890;
        return g;
    }

    function circle(cx, cy, cz, r, colour, segments) {
        var pts = [], i, n = segments || 40;
        for (i = 0; i < n; i++) {
            pts.push([cx + Math.cos(i / n * 6.283) * r, cy, cz + Math.sin(i / n * 6.283) * r]);
        }
        return line(pts, colour, true);
    }

    function build(hole) {
        var g = new THREE.Group();
        var i, w, authored = hole.extra || [];
        D.movers = [];

        // One line a metre, through the origin: every number in courses.js is
        // a measurement from there, so that is where the ruler starts.
        var span = Math.ceil(Math.max(
            hole.bounds.maxX - hole.bounds.minX, hole.bounds.maxZ - hole.bounds.minZ) + 8);
        var grid = new THREE.GridHelper(span, span, COLOUR.grid, COLOUR.grid);
        grid.position.set(span / 2, -0.02, span / 2);
        grid.material.transparent = true;
        grid.material.opacity = 0.16;
        grid.material.depthTest = false;
        grid.renderOrder = 890;
        g.add(grid);

        for (i = 0; i < hole.pads.length; i++) {
            g.add(padFill(hole.pads[i], i));
            g.add(padOutline(hole.pads[i]));
        }

        for (i = 0; i < hole.walls.length; i++) {
            w = hole.walls[i];
            var l = wallOutline(w, authored.indexOf(w) >= 0);
            g.add(l);
            D.movers.push({ line: l, wall: w, h: w.h });
        }

        for (i = 0; i < hole.water.length; i++) {
            g.add(rectOutline(hole.water[i], hole.water[i].y + 0.01, COLOUR.water));
        }

        /* A gap is a rectangle inside which enclose() built no rail, so it
           belongs on the ground it opened up — sampled at its own middle,
           because that is the pad it was drawn against — and lifted clear of
           the kerb it replaced, so it is not swallowed by the one rail that
           did get built at the corner. */
        for (i = 0; i < (hole.gaps || []).length; i++) {
            var r = hole.gaps[i];
            var top = P.surfaceTop(hole, r.x + r.w / 2, r.z + r.d / 2);
            g.add(rectOutline(r, (top ? top.y : hole.cup.y) + 0.5, COLOUR.gap));
        }

        // The rim, and the clearance the tests want inside the pad edge round
        // it: a cup any closer to an edge than the outer ring is a hole the
        // renderer cannot punch and the physics cannot hold.
        g.add(circle(hole.cup.x, hole.cup.y + 0.02, hole.cup.z, C.HOLE_R, COLOUR.cup));
        g.add(circle(hole.cup.x, hole.cup.y + 0.02, hole.cup.z, C.HOLE_R + 0.05, COLOUR.cup, 64));
        g.add(circle(hole.tee.x, hole.tee.y + 0.02, hole.tee.z, 0.3, COLOUR.tee));

        return g;
    }

    // The outlines that move, placed from the same call the solver makes.
    function syncWalls(t) {
        var i, m, B;
        for (i = 0; i < D.movers.length; i++) {
            m = D.movers[i];
            B = P.wallBox(m.wall, t);
            m.line.position.set(B.cx, B.base + m.h / 2, B.cz);
            m.line.rotation.y = B.yaw;
        }
    }

    /* ── where the pointer is ───────────────────────────────────────────── */

    /* Against the pads themselves rather than a flat plane, because the number
       you want on a ramp is the point on the ramp. A pad is a plane, so this
       is one division per pad and then the footprint test the solver uses. */
    var _ray = new THREE.Raycaster();
    var _ndc = new THREE.Vector2();

    function under(hole, camera, nx, ny) {
        _ray.setFromCamera(_ndc.set(nx, ny), camera);
        var o = _ray.ray.origin, d = _ray.ray.direction;
        var best = null, bestT = Infinity, i, pad, den, t, x, z;

        for (i = 0; i < hole.pads.length; i++) {
            pad = hole.pads[i];
            den = d.y - (pad.sx || 0) * d.x - (pad.sz || 0) * d.z;
            if (Math.abs(den) < 1e-9) continue;
            t = (P.padHeight(pad, o.x, o.z) - o.y) / den;
            if (t <= 0 || t >= bestT) continue;
            x = o.x + d.x * t; z = o.z + d.z * t;
            if (!P.padContains(pad, x, z)) continue;
            bestT = t;
            best = { x: x, y: P.padHeight(pad, x, z), z: z, pad: i, kind: pad.kind };
        }
        if (best) return best;

        // Off the course: fall back to y = 0, which is the plane the pads are
        // written in, so pointing at the water still gives usable numbers.
        if (Math.abs(d.y) < 1e-9) return null;
        t = -o.y / d.y;
        if (t <= 0) return null;
        return { x: o.x + d.x * t, y: 0, z: o.z + d.z * t, pad: -1, kind: 'off' };
    }

    /* ── the lint ───────────────────────────────────────────────────────── */

    /* The same five rules tests.html asserts, brought forward to where the
       hole is being edited. tests.html stays the authority — it also plays the
       hole, which is the only check that matters and the only one that cannot
       be done in a panel. */
    function lint(hole) {
        var out = [], i, j;

        var thin = null;
        for (i = 0; i < hole.walls.length; i++) {
            var t = Math.min(hole.walls[i].w, hole.walls[i].d);
            if (t < 0.24 && (thin === null || t < thin)) thin = t;
        }
        if (thin !== null) out.push('wall thinner than 0.24 (' + thin.toFixed(3) + ') — the ball can tunnel it');

        var own = null;
        for (i = 0; i < hole.pads.length; i++) {
            if (P.padContains(hole.pads[i], hole.cup.x, hole.cup.z) &&
                Math.abs(P.padHeight(hole.pads[i], hole.cup.x, hole.cup.z) - hole.cup.y) < 0.06) own = hole.pads[i];
        }
        var clear = own ? Math.min(hole.cup.x - own.x, own.x + own.w - hole.cup.x,
                                   hole.cup.z - own.z, own.z + own.d - hole.cup.z) : 0;
        if (!(clear > C.HOLE_R + 0.05)) {
            out.push('the cup is ' + clear.toFixed(2) + ' from its pad edge, needs over ' + (C.HOLE_R + 0.05).toFixed(2));
        }

        var teeBlocked = false, cupBlocked = false;
        for (i = 0; i < hole.walls.length; i++) {
            var B = P.wallBox(hole.walls[i], 0);
            if (hole.tee.y + C.BALL_R > B.base && hole.tee.y < B.top &&
                P.circleBox(hole.tee.x, hole.tee.z, C.BALL_R, B)) teeBlocked = true;
            if (hole.cup.y + C.BALL_R > B.base && hole.cup.y < B.top &&
                P.circleBox(hole.cup.x, hole.cup.z, C.HOLE_R, B)) cupBlocked = true;
        }
        if (teeBlocked) out.push('the tee is inside a wall');
        if (cupBlocked) out.push('the cup is inside a wall');

        for (i = 0; i < hole.pads.length; i++) {
            for (j = i + 1; j < hole.pads.length; j++) {
                var a = hole.pads[i], b = hole.pads[j];
                var ox = Math.min(a.x + a.w, b.x + b.w) - Math.max(a.x, b.x);
                var oz = Math.min(a.z + a.d, b.z + b.d) - Math.max(a.z, b.z);
                if (ox <= 1e-9 || oz <= 1e-9) continue;      // touching is fine
                var mx = Math.max(a.x, b.x) + ox / 2, mz = Math.max(a.z, b.z) + oz / 2;
                if (Math.abs(P.padHeight(a, mx, mz) - P.padHeight(b, mx, mz)) < 0.35) {
                    out.push('pads ' + i + ' and ' + j + ' fight for the same ground');
                }
            }
        }
        return out;
    }

    /* ── the panel ──────────────────────────────────────────────────────── */

    var CSS =
        '#g3-debug{position:absolute;top:8px;left:8px;z-index:40;max-width:min(340px,52vw);' +
        'font:11px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;color:#dfe7ee;' +
        'background:rgba(10,14,20,.82);border:1px solid rgba(255,255,255,.14);border-radius:8px;' +
        'padding:8px 10px;pointer-events:none;white-space:pre-wrap;backdrop-filter:blur(4px)}' +
        '#g3-debug b{color:#fff;font-weight:600}' +
        '#g3-debug .bad{color:#ff8f8f}' +
        '#g3-debug .dim{color:#8fa0b0}';

    function panel() {
        if (D.panel) return D.panel;
        var st = document.createElement('style');
        st.textContent = CSS;
        document.head.appendChild(st);
        var el = document.createElement('div');
        el.id = 'g3-debug';
        (document.getElementById('stage') || document.body).appendChild(el);
        D.panel = el;
        return el;
    }

    function census(scene) {
        var meshes = 0, mats = [], texs = [];
        scene.traverse(function (o) {
            if (!o.isMesh) return;
            meshes++;
            var ms = Array.isArray(o.material) ? o.material : [o.material];
            ms.forEach(function (m) {
                if (!m || mats.indexOf(m) >= 0) return;
                mats.push(m);
                ['map', 'bumpMap', 'normalMap'].forEach(function (k) {
                    if (m[k] && texs.indexOf(m[k]) < 0) texs.push(m[k]);
                });
            });
        });
        return { meshes: meshes, mats: mats.length, texs: texs.length };
    }

    function esc(s) { return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;'); }

    function write(hole, state) {
        var R = G3.render, S = R.state;
        var c = census(S.holeGroup || S.scene);
        var rails = 0, i;
        var authored = hole.extra || [];
        for (i = 0; i < hole.walls.length; i++) if (authored.indexOf(hole.walls[i]) < 0) rails++;

        var p = D.point;
        var rows = [
            '<b>' + esc(hole.name) + '</b> <span class="dim">' + esc(state.course.name) +
                ' · hole ' + (state.holeIndex + 1) + ' · par ' + hole.par + '</span>',
            p
                ? 'at  <b>x ' + p.x.toFixed(2) + '  z ' + p.z.toFixed(2) + '</b>  y ' + p.y.toFixed(2) +
                  '  <span class="dim">' + (p.pad < 0 ? 'off the course' : 'pad ' + p.pad + ' · ' + p.kind) + '</span>'
                : '<span class="dim">point at the course for coordinates</span>',
            '<span class="dim">' + D.fps + ' fps · ' + D.ms.toFixed(1) + ' ms · worst ' +
                D.worst.toFixed(1) + ' ms · ' + (S.pathBuilds || 0) + ' path builds</span>',
            '<span class="dim">' + hole.pads.length + ' pads · ' + rails + ' rails + ' +
                authored.length + ' authored · ' + hole.water.length + ' water · ' +
                (hole.gaps || []).length + ' gaps</span>',
            '<span class="dim">' + c.meshes + ' meshes · ' + c.mats + ' materials · ' +
                c.texs + ' textures</span>'
        ];
        var problems = lint(hole);
        if (problems.length) {
            rows.push('<span class="bad">' + problems.map(esc).join('<br>') + '</span>');
        } else {
            rows.push('<span class="dim">lint clean — tests.html still has the last word</span>');
        }
        rows.push('<span class="dim">G hides this · debug.dump() prints the hole</span>');
        D.panel.innerHTML = rows.join('<br>');
    }

    /* ── wiring ─────────────────────────────────────────────────────────── */

    function drop() {
        if (!D.group) return;
        D.group.traverse(function (o) {
            if (o.geometry) o.geometry.dispose();
            if (o.material) o.material.dispose();
        });
        G3.render.state.scene.remove(D.group);
        D.group = null;
        D.hole = null;
        D.movers = [];
    }

    function show(on) {
        D.on = !!on;
        if (D.panel) D.panel.style.display = D.on ? '' : 'none';
        if (!D.on) drop();
        else panel().style.display = '';
    }

    function toggle() { show(!D.on); return D.on; }

    function frame(world, dt) {
        if (!D.on || !world || !G3.render || !G3.render.state.ready) return;
        var S = G3.render.state;

        if (D.hole !== world.hole) {
            drop();
            D.group = build(world.hole);
            S.scene.add(D.group);
            D.hole = world.hole;
        }
        syncWalls(world.time);

        if (D.pointer) D.point = under(world.hole, S.camera, D.pointer.x, D.pointer.y);

        D.frames++;
        D.acc += dt;
        D.worst = Math.max(D.worst, dt * 1000);
        // Numbers that flicker faster than they can be read are decoration.
        if (D.acc >= 0.5) {
            D.fps = Math.round(D.frames / D.acc);
            D.ms = (D.acc / D.frames) * 1000;
            var st = G3.game && G3.game.state;
            if (st && st.course) write(st.course.holes[st.holeIndex], st);
            D.frames = 0; D.acc = 0; D.worst = 0;
            S.pathBuilds = 0;
        }
    }

    /* The hole, printed the way courses.js writes one, so a shape worked out
       by pointing at the screen can be pasted straight back into the file.

       It prints what was authored — the pads, the water, the gaps, the `extra`
       walls, the tee and the cup — and not the rails, because those are
       generated and printing them would turn a hole that follows its own floor
       into a hole with forty boxes nailed to it. It also prints primitives
       rather than the sugar: a `beam()` comes back out as the three walls it
       is, and a `bowl()` as its nine pads. That is the honest thing for it to
       do, since primitives are what the hole actually is by the time anything
       here can see it. */
    function dump() {
        var st = G3.game && G3.game.state;
        if (!st || !st.course) return '';
        var h = st.course.holes[st.holeIndex];
        function n(v) { return (Math.round(v * 1000) / 1000); }
        function rect(r) {
            return 'rect(' + [n(r.x), n(r.z), n(r.w), n(r.d)].join(', ') +
                (r.y === undefined ? '' : ', ' + n(r.y)) + ')';
        }
        var out = ['build({',
            "    name: '" + h.name + "', par: " + h.par + ",",
            "    blurb: '" + h.blurb.replace(/'/g, "\\'") + "',",
            '    pads: [' + h.pads.map(function (p) {
                return 'pad(' + [n(p.x), n(p.z), n(p.w), n(p.d), n(p.y)].join(', ') +
                    ", '" + p.kind + "'" + (p.sx || p.sz ? ', ' + n(p.sx) + ', ' + n(p.sz) : '') + ')';
            }).join(', ') + '],'];
        if (h.water.length) out.push('    water: [' + h.water.map(rect).join(', ') + '],');
        if ((h.gaps || []).length) out.push('    gaps: [' + h.gaps.map(rect).join(', ') + '],');
        if ((h.extra || []).length) {
            out.push('    extra: [' + h.extra.map(function (w) {
                var o = [];
                if (w.base !== -0.4) o.push('base: ' + n(w.base));
                if (w.yaw) o.push('yaw: ' + n(w.yaw));
                if (w.spin) o.push('spin: ' + n(w.spin));
                if (w.kind !== 'rail') o.push("kind: '" + w.kind + "'");
                if (w.move) {
                    o.push("move: { axis: '" + w.move.axis + "', amp: " + n(w.move.amp) +
                        ', speed: ' + n(w.move.speed) + ', phase: ' + n(w.move.phase) + ' }');
                }
                return 'wall(' + [n(w.x), n(w.z), n(w.w), n(w.d), n(w.h)].join(', ') +
                    (o.length ? ', { ' + o.join(', ') + ' }' : '') + ')';
            }).join(',\n            ') + '],');
        }
        out.push('    tee: { x: ' + n(h.tee.x) + ', z: ' + n(h.tee.z) + ' }, ' +
                 'cup: { x: ' + n(h.cup.x) + ', z: ' + n(h.cup.z) + ' }');
        out.push('})');
        var text = out.join('\n');
        if (window.console) console.log(text);
        return text;
    }

    function init(canvas) {
        D.canvas = canvas;
        canvas.addEventListener('pointermove', function (e) {
            if (!D.on) return;
            var r = canvas.getBoundingClientRect();
            D.pointer = D.pointer || new THREE.Vector2();
            D.pointer.set(
                ((e.clientX - r.left) / r.width) * 2 - 1,
                -((e.clientY - r.top) / r.height) * 2 + 1
            );
        });
        canvas.addEventListener('pointerleave', function () { D.pointer = null; D.point = null; });
        window.addEventListener('keydown', function (e) {
            if (e.key === 'g' || e.key === 'G') {
                if (e.target && /input|textarea/i.test(e.target.tagName)) return;
                toggle();
            }
        });
        if (/(^|[?&])debug=1(&|$)/.test(window.location.search)) show(true);
    }

    G3.debug = {
        init: init,
        frame: frame,
        toggle: toggle,
        lint: lint,
        dump: dump,
        get on() { return D.on; },
        state: D
    };

})(window.G3);
